apiVersion: v1
kind: Pod
metadata:
  name: barramento
spec:
  containers:
    - name: barramento
      image: nalu/barramento:0.0.1
      resources:
        limits:
          memory: 256Mi
          cpu: 1