apiVersion: v1
kind: Service
metadata:
  name: barramento-service
spec:
  type: NodePort
  selector:
    app: barramento
  ports:
    - name: barramento
      protocol: TCP
      port: 10000
      targetPort: 10000