apiVersion: v1
kind: Pod
metadata:
  name: classificacao
spec:
  containers:
    - name: classificacao
      image: nalu/classificacao:0.0.1
      resources:
        limits:
          memory: 256Mi
          cpu: 1