apiVersion: apps/v1
kind: Deployment
metadata:
  name: lembretes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lembretes
  template:
    metadata:
      labels:
        app: lembretes
    spec:
      containers:
        - name: lembretes
          image: nalu/lembretes
          imagePullPolicy: Never
          resources:
            limits:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: lembretes-service
spec:
  selector:
    app: lembretes
  ports:
    - name: lembretes
      protocol: TCP
      port: 4000
      targetPort: 4000