apiVersion: apps/v1
kind: Deployment
metadata:
  name: observacoes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observacoes
  template:
    metadata:
      labels:
        app: observacoes
    spec:
      containers:
        - name: observacoes
          image: nalu/observacoes
---
apiVersion: v1
kind: Service
metadata:
  name: observacoes-service
spec:
  selector:
    app: observacoes
  type: ClusterIP
  ports:
    - name: observacoes
      protocol: TCP
      port: 5000
      targetPort: 5000